POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "user1",
  "password": "pass1"
}

####
#PUT https://chalkling.herokuapp.com/api/logout
####
GET http://localhost:5000/api/login
###
PUT http://localhost:5000/api/message
Content-Type: application/json

{
  "messageType": "DIRECT",
  "receiverName": "user3",
  "content": "test!"
}
###
POST http://localhost:5000/api/message
Content-Type: application/json

{
  "messageType": "DIRECT",
  "receiverName": "user2"
}
###
POST http://localhost:5000/api/message
Content-Type: application/json

{
  "messageType": "DIRECT",
  "receiverName": "user3"
}